services:
  memory-bucket-api:
    container_name: memory-bucket
    image: aprileaf/memory-bucket
    ports:
      - 8080:8080
    env_file: ./.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    env_file:
      - path: ./.env
    ports:
      - 5432:5432
    volumes:
      - ~/memory-bucket/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d api" ]
      interval: 10s
      timeout: 5s
      retries: 5
