name: Deploy To Develop Server

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 로드
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.APP_ENV }}" > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: aprileaf/memory-bucket-api:latest
          file: ./api/Dockerfile

      - name: Set up docker context over SSH authentication
        uses: amirmarmul/docker-context-ssh-action@v2.1.3
        with:
          ssh-host: ${{ secrets.NCLOUD_HOST }}
          ssh-username: ${{ secrets.NCLOUD_USERNAME }}
          ssh-private-key: ${{ secrets.NCLOUD_PRIVATE_KEY }}
          ssh-port: ${{ secrets.NCLOUD_PORT }}

      - name: Use Remote Context
        run: docker context use remote

      - name: Docker compose pull
        run: docker compose pull

      - name: Docker compose up
        run: docker compose up -d


